// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commpb.proto

package commpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VoteRsp_VtRes int32

const (
	VoteRsp_NO  VoteRsp_VtRes = 0
	VoteRsp_YES VoteRsp_VtRes = 1
)

var VoteRsp_VtRes_name = map[int32]string{
	0: "NO",
	1: "YES",
}

var VoteRsp_VtRes_value = map[string]int32{
	"NO":  0,
	"YES": 1,
}

func (x VoteRsp_VtRes) String() string {
	return proto.EnumName(VoteRsp_VtRes_name, int32(x))
}

func (VoteRsp_VtRes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2eb5c7490bed74a, []int{1, 0}
}

type VoteReq struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	LastLogTerm          int64    `protobuf:"varint,3,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	LastLogId            int64    `protobuf:"varint,4,opt,name=last_log_id,json=lastLogId,proto3" json:"last_log_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteReq) Reset()         { *m = VoteReq{} }
func (m *VoteReq) String() string { return proto.CompactTextString(m) }
func (*VoteReq) ProtoMessage()    {}
func (*VoteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2eb5c7490bed74a, []int{0}
}

func (m *VoteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteReq.Unmarshal(m, b)
}
func (m *VoteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteReq.Marshal(b, m, deterministic)
}
func (m *VoteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteReq.Merge(m, src)
}
func (m *VoteReq) XXX_Size() int {
	return xxx_messageInfo_VoteReq.Size(m)
}
func (m *VoteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteReq.DiscardUnknown(m)
}

var xxx_messageInfo_VoteReq proto.InternalMessageInfo

func (m *VoteReq) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *VoteReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VoteReq) GetLastLogTerm() int64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

func (m *VoteReq) GetLastLogId() int64 {
	if m != nil {
		return m.LastLogId
	}
	return 0
}

type VoteRsp struct {
	Vtres                VoteRsp_VtRes `protobuf:"varint,1,opt,name=vtres,proto3,enum=VoteRsp_VtRes" json:"vtres,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *VoteRsp) Reset()         { *m = VoteRsp{} }
func (m *VoteRsp) String() string { return proto.CompactTextString(m) }
func (*VoteRsp) ProtoMessage()    {}
func (*VoteRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2eb5c7490bed74a, []int{1}
}

func (m *VoteRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteRsp.Unmarshal(m, b)
}
func (m *VoteRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteRsp.Marshal(b, m, deterministic)
}
func (m *VoteRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteRsp.Merge(m, src)
}
func (m *VoteRsp) XXX_Size() int {
	return xxx_messageInfo_VoteRsp.Size(m)
}
func (m *VoteRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteRsp.DiscardUnknown(m)
}

var xxx_messageInfo_VoteRsp proto.InternalMessageInfo

func (m *VoteRsp) GetVtres() VoteRsp_VtRes {
	if m != nil {
		return m.Vtres
	}
	return VoteRsp_NO
}

type HBReq struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HBReq) Reset()         { *m = HBReq{} }
func (m *HBReq) String() string { return proto.CompactTextString(m) }
func (*HBReq) ProtoMessage()    {}
func (*HBReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2eb5c7490bed74a, []int{2}
}

func (m *HBReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HBReq.Unmarshal(m, b)
}
func (m *HBReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HBReq.Marshal(b, m, deterministic)
}
func (m *HBReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HBReq.Merge(m, src)
}
func (m *HBReq) XXX_Size() int {
	return xxx_messageInfo_HBReq.Size(m)
}
func (m *HBReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HBReq.DiscardUnknown(m)
}

var xxx_messageInfo_HBReq proto.InternalMessageInfo

func (m *HBReq) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *HBReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type HBRsp struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HBRsp) Reset()         { *m = HBRsp{} }
func (m *HBRsp) String() string { return proto.CompactTextString(m) }
func (*HBRsp) ProtoMessage()    {}
func (*HBRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2eb5c7490bed74a, []int{3}
}

func (m *HBRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HBRsp.Unmarshal(m, b)
}
func (m *HBRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HBRsp.Marshal(b, m, deterministic)
}
func (m *HBRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HBRsp.Merge(m, src)
}
func (m *HBRsp) XXX_Size() int {
	return xxx_messageInfo_HBRsp.Size(m)
}
func (m *HBRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_HBRsp.DiscardUnknown(m)
}

var xxx_messageInfo_HBRsp proto.InternalMessageInfo

func (m *HBRsp) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

type Msg struct {
	Type                 int64    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2eb5c7490bed74a, []int{4}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

type CP struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Nodeid               int64    `protobuf:"varint,3,opt,name=nodeid,proto3" json:"nodeid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CP) Reset()         { *m = CP{} }
func (m *CP) String() string { return proto.CompactTextString(m) }
func (*CP) ProtoMessage()    {}
func (*CP) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2eb5c7490bed74a, []int{5}
}

func (m *CP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CP.Unmarshal(m, b)
}
func (m *CP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CP.Marshal(b, m, deterministic)
}
func (m *CP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CP.Merge(m, src)
}
func (m *CP) XXX_Size() int {
	return xxx_messageInfo_CP.Size(m)
}
func (m *CP) XXX_DiscardUnknown() {
	xxx_messageInfo_CP.DiscardUnknown(m)
}

var xxx_messageInfo_CP proto.InternalMessageInfo

func (m *CP) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CP) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CP) GetNodeid() int64 {
	if m != nil {
		return m.Nodeid
	}
	return 0
}

type Commit struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Term                 int64    `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	LastTerm             int64    `protobuf:"varint,4,opt,name=last_term,json=lastTerm,proto3" json:"last_term,omitempty"`
	LastId               int64    `protobuf:"varint,5,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	SrcId                int64    `protobuf:"varint,6,opt,name=src_id,json=srcId,proto3" json:"src_id,omitempty"`
	Type                 int64    `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	LastMemTerm          int64    `protobuf:"varint,8,opt,name=last_mem_term,json=lastMemTerm,proto3" json:"last_mem_term,omitempty"`
	LastMemId            int64    `protobuf:"varint,9,opt,name=last_mem_id,json=lastMemId,proto3" json:"last_mem_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2eb5c7490bed74a, []int{6}
}

func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (m *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(m, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Commit) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Commit) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Commit) GetLastTerm() int64 {
	if m != nil {
		return m.LastTerm
	}
	return 0
}

func (m *Commit) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

func (m *Commit) GetSrcId() int64 {
	if m != nil {
		return m.SrcId
	}
	return 0
}

func (m *Commit) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Commit) GetLastMemTerm() int64 {
	if m != nil {
		return m.LastMemTerm
	}
	return 0
}

func (m *Commit) GetLastMemId() int64 {
	if m != nil {
		return m.LastMemId
	}
	return 0
}

func init() {
	proto.RegisterEnum("VoteRsp_VtRes", VoteRsp_VtRes_name, VoteRsp_VtRes_value)
	proto.RegisterType((*VoteReq)(nil), "VoteReq")
	proto.RegisterType((*VoteRsp)(nil), "VoteRsp")
	proto.RegisterType((*HBReq)(nil), "HBReq")
	proto.RegisterType((*HBRsp)(nil), "HBRsp")
	proto.RegisterType((*Msg)(nil), "Msg")
	proto.RegisterType((*CP)(nil), "CP")
	proto.RegisterType((*Commit)(nil), "Commit")
}

func init() {
	proto.RegisterFile("commpb.proto", fileDescriptor_d2eb5c7490bed74a)
}

var fileDescriptor_d2eb5c7490bed74a = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x5f, 0x6b, 0xdb, 0x3c,
	0x14, 0xc6, 0x13, 0x3b, 0xb1, 0x93, 0xd3, 0x34, 0x6f, 0x11, 0xbc, 0x9b, 0x9b, 0xec, 0x1f, 0x62,
	0x17, 0x83, 0x81, 0x18, 0xdd, 0x27, 0x58, 0xcc, 0xd6, 0x04, 0x9a, 0xcd, 0xb8, 0xa5, 0xb0, 0xab,
	0xe2, 0x58, 0x67, 0x9e, 0x68, 0x14, 0xb9, 0x92, 0x32, 0xd6, 0x0f, 0xbb, 0xcb, 0x7d, 0x8f, 0x21,
	0xd9, 0x4d, 0x18, 0xe9, 0xc5, 0xae, 0x7c, 0xce, 0xf9, 0x3d, 0xf6, 0xd1, 0x39, 0x8f, 0x05, 0xa3,
	0x52, 0x49, 0x59, 0xaf, 0x58, 0xad, 0x95, 0x55, 0xf4, 0x0e, 0xe2, 0x6b, 0x65, 0x31, 0xc7, 0x3b,
	0x42, 0xa0, 0x67, 0x51, 0xcb, 0xa4, 0xfb, 0xaa, 0xfb, 0x26, 0xcc, 0x7d, 0x4c, 0xc6, 0x10, 0x08,
	0x9e, 0x04, 0xbe, 0x12, 0x08, 0x4e, 0x28, 0x1c, 0xaf, 0x0b, 0x63, 0x6f, 0xd6, 0xaa, 0xba, 0xf1,
	0xe2, 0xd0, 0xa3, 0x23, 0x57, 0xbc, 0x50, 0xd5, 0x95, 0x7b, 0xe7, 0x05, 0x1c, 0xed, 0x34, 0x82,
	0x27, 0x3d, 0xaf, 0x18, 0xb6, 0x8a, 0x05, 0xa7, 0x8b, 0xb6, 0xa5, 0xa9, 0xc9, 0x6b, 0xe8, 0xff,
	0xb0, 0x1a, 0x8d, 0xef, 0x39, 0x3e, 0x1b, 0xb3, 0x16, 0xb0, 0x6b, 0x9b, 0xa3, 0xc9, 0x1b, 0x48,
	0x13, 0xe8, 0xfb, 0x9c, 0x44, 0x10, 0x7c, 0xfe, 0x72, 0xd2, 0x21, 0x31, 0x84, 0x5f, 0x3f, 0x5e,
	0x9e, 0x74, 0xe9, 0x5b, 0xe8, 0xcf, 0x67, 0xff, 0x78, 0x76, 0x3a, 0xf5, 0x62, 0x53, 0x3f, 0x26,
	0xa6, 0xa7, 0x10, 0x2e, 0x4d, 0xe5, 0xd1, 0x7d, 0x8d, 0x3b, 0x74, 0x5f, 0x23, 0x9d, 0x43, 0x90,
	0x66, 0x8e, 0xf0, 0xc2, 0x16, 0x9e, 0x8c, 0x72, 0x1f, 0x93, 0x27, 0x10, 0x19, 0x5b, 0xd8, 0xad,
	0x69, 0xbb, 0xb4, 0x99, 0xab, 0x6f, 0x14, 0x47, 0xc1, 0xdb, 0xf5, 0xb4, 0x19, 0xfd, 0xdd, 0x85,
	0x28, 0x55, 0x52, 0x0a, 0xfb, 0xe8, 0xe7, 0x1e, 0xce, 0x15, 0x1c, 0x0c, 0x11, 0xee, 0x0c, 0x98,
	0x82, 0xdf, 0x64, 0xb3, 0xfc, 0x66, 0xb5, 0x03, 0x57, 0xf0, 0x9b, 0x7f, 0x0a, 0xb1, 0x87, 0x82,
	0x27, 0xfd, 0xa6, 0xb1, 0x4b, 0x17, 0x9c, 0xfc, 0x0f, 0x91, 0xd1, 0xa5, 0xab, 0x47, 0xbe, 0xde,
	0x37, 0xba, 0x5c, 0xf0, 0xdd, 0xb4, 0xf1, 0x7e, 0xda, 0x9d, 0xc3, 0x12, 0x65, 0xd3, 0x64, 0xb0,
	0x77, 0x78, 0x89, 0xf2, 0x2f, 0x87, 0x9d, 0x46, 0xf0, 0x64, 0xb8, 0x77, 0x78, 0x89, 0x72, 0xc1,
	0xcf, 0x7e, 0xb5, 0x73, 0xd6, 0x2b, 0x42, 0x01, 0x3e, 0x98, 0xdb, 0x4f, 0x4a, 0x3b, 0x67, 0xc9,
	0x80, 0xb5, 0x3f, 0xdb, 0x64, 0xf0, 0x60, 0x35, 0xed, 0x90, 0xe7, 0x30, 0x9c, 0x63, 0xa1, 0xed,
	0x0c, 0x0b, 0x4b, 0x22, 0xe6, 0x1d, 0x9d, 0xf8, 0xa7, 0xc7, 0xcf, 0xe0, 0xf8, 0x1c, 0x6d, 0xfa,
	0x1d, 0xcb, 0xdb, 0x4c, 0x89, 0x8d, 0x25, 0x3d, 0xb6, 0x34, 0xd5, 0x24, 0x64, 0x69, 0x46, 0x3b,
	0x64, 0x02, 0x71, 0xa6, 0xb1, 0x2e, 0x34, 0x92, 0x98, 0x35, 0xcb, 0x9d, 0x78, 0x41, 0xc3, 0x52,
	0xb5, 0xf9, 0x26, 0xb4, 0x3c, 0x64, 0xa7, 0x10, 0xa5, 0xc5, 0xa6, 0xc4, 0xf5, 0x21, 0x7a, 0x09,
	0xa3, 0x4b, 0xdc, 0xf0, 0x2b, 0x75, 0x81, 0x05, 0x47, 0x7d, 0x20, 0x98, 0xbd, 0x83, 0xa9, 0x50,
	0xac, 0xd2, 0x75, 0xc9, 0xf0, 0x67, 0x21, 0xeb, 0x35, 0x1a, 0xa6, 0xd5, 0xd6, 0x62, 0xb5, 0x15,
	0x1c, 0x67, 0xff, 0xe5, 0x2e, 0x3e, 0x77, 0x71, 0xe6, 0x2e, 0x59, 0xd6, 0x5d, 0x45, 0xfe, 0xb6,
	0xbd, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x9e, 0x1f, 0x5c, 0x7d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CommpbClient is the client API for Commpb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommpbClient interface {
	AskForVote(ctx context.Context, in *VoteReq, opts ...grpc.CallOption) (*VoteRsp, error)
	HeartBeat(ctx context.Context, in *HBReq, opts ...grpc.CallOption) (*HBRsp, error)
	GetCheckPoint(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*CP, error)
	Prepare(ctx context.Context, in *Commit, opts ...grpc.CallOption) (*Msg, error)
	Confirm(ctx context.Context, in *Commit, opts ...grpc.CallOption) (*Msg, error)
	Cancel(ctx context.Context, in *Commit, opts ...grpc.CallOption) (*Msg, error)
	SendToLeader(ctx context.Context, in *Commit, opts ...grpc.CallOption) (*Msg, error)
}

type commpbClient struct {
	cc grpc.ClientConnInterface
}

func NewCommpbClient(cc grpc.ClientConnInterface) CommpbClient {
	return &commpbClient{cc}
}

func (c *commpbClient) AskForVote(ctx context.Context, in *VoteReq, opts ...grpc.CallOption) (*VoteRsp, error) {
	out := new(VoteRsp)
	err := c.cc.Invoke(ctx, "/Commpb/AskForVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commpbClient) HeartBeat(ctx context.Context, in *HBReq, opts ...grpc.CallOption) (*HBRsp, error) {
	out := new(HBRsp)
	err := c.cc.Invoke(ctx, "/Commpb/HeartBeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commpbClient) GetCheckPoint(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*CP, error) {
	out := new(CP)
	err := c.cc.Invoke(ctx, "/Commpb/GetCheckPoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commpbClient) Prepare(ctx context.Context, in *Commit, opts ...grpc.CallOption) (*Msg, error) {
	out := new(Msg)
	err := c.cc.Invoke(ctx, "/Commpb/Prepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commpbClient) Confirm(ctx context.Context, in *Commit, opts ...grpc.CallOption) (*Msg, error) {
	out := new(Msg)
	err := c.cc.Invoke(ctx, "/Commpb/Confirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commpbClient) Cancel(ctx context.Context, in *Commit, opts ...grpc.CallOption) (*Msg, error) {
	out := new(Msg)
	err := c.cc.Invoke(ctx, "/Commpb/Cancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commpbClient) SendToLeader(ctx context.Context, in *Commit, opts ...grpc.CallOption) (*Msg, error) {
	out := new(Msg)
	err := c.cc.Invoke(ctx, "/Commpb/SendToLeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommpbServer is the server API for Commpb service.
type CommpbServer interface {
	AskForVote(context.Context, *VoteReq) (*VoteRsp, error)
	HeartBeat(context.Context, *HBReq) (*HBRsp, error)
	GetCheckPoint(context.Context, *Msg) (*CP, error)
	Prepare(context.Context, *Commit) (*Msg, error)
	Confirm(context.Context, *Commit) (*Msg, error)
	Cancel(context.Context, *Commit) (*Msg, error)
	SendToLeader(context.Context, *Commit) (*Msg, error)
}

// UnimplementedCommpbServer can be embedded to have forward compatible implementations.
type UnimplementedCommpbServer struct {
}

func (*UnimplementedCommpbServer) AskForVote(ctx context.Context, req *VoteReq) (*VoteRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AskForVote not implemented")
}
func (*UnimplementedCommpbServer) HeartBeat(ctx context.Context, req *HBReq) (*HBRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}
func (*UnimplementedCommpbServer) GetCheckPoint(ctx context.Context, req *Msg) (*CP, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCheckPoint not implemented")
}
func (*UnimplementedCommpbServer) Prepare(ctx context.Context, req *Commit) (*Msg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (*UnimplementedCommpbServer) Confirm(ctx context.Context, req *Commit) (*Msg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Confirm not implemented")
}
func (*UnimplementedCommpbServer) Cancel(ctx context.Context, req *Commit) (*Msg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cancel not implemented")
}
func (*UnimplementedCommpbServer) SendToLeader(ctx context.Context, req *Commit) (*Msg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToLeader not implemented")
}

func RegisterCommpbServer(s *grpc.Server, srv CommpbServer) {
	s.RegisterService(&_Commpb_serviceDesc, srv)
}

func _Commpb_AskForVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommpbServer).AskForVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Commpb/AskForVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommpbServer).AskForVote(ctx, req.(*VoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commpb_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HBReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommpbServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Commpb/HeartBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommpbServer).HeartBeat(ctx, req.(*HBReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commpb_GetCheckPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommpbServer).GetCheckPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Commpb/GetCheckPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommpbServer).GetCheckPoint(ctx, req.(*Msg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commpb_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Commit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommpbServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Commpb/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommpbServer).Prepare(ctx, req.(*Commit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commpb_Confirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Commit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommpbServer).Confirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Commpb/Confirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommpbServer).Confirm(ctx, req.(*Commit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commpb_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Commit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommpbServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Commpb/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommpbServer).Cancel(ctx, req.(*Commit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commpb_SendToLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Commit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommpbServer).SendToLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Commpb/SendToLeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommpbServer).SendToLeader(ctx, req.(*Commit))
	}
	return interceptor(ctx, in, info, handler)
}

var _Commpb_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Commpb",
	HandlerType: (*CommpbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AskForVote",
			Handler:    _Commpb_AskForVote_Handler,
		},
		{
			MethodName: "HeartBeat",
			Handler:    _Commpb_HeartBeat_Handler,
		},
		{
			MethodName: "GetCheckPoint",
			Handler:    _Commpb_GetCheckPoint_Handler,
		},
		{
			MethodName: "Prepare",
			Handler:    _Commpb_Prepare_Handler,
		},
		{
			MethodName: "Confirm",
			Handler:    _Commpb_Confirm_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Commpb_Cancel_Handler,
		},
		{
			MethodName: "SendToLeader",
			Handler:    _Commpb_SendToLeader_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commpb.proto",
}
